"""Update models with correct table names and relationships

Revision ID: 54f3008e1692
Revises: 3d46f876b2d6
Create Date: 2024-07-30 16:50:49.356106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f3008e1692'
down_revision: Union[str, None] = '3d46f876b2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('magazines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('magazines', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('magazines', 'discount_quarterly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('magazines', 'discount_half_yearly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('magazines', 'discount_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index('ix_magazines_name', table_name='magazines')
    op.create_index(op.f('ix_magazines_name'), 'magazines', ['name'], unique=True)
    op.drop_column('magazines', 'discount_monthly')
    op.alter_column('plans', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plans', 'renewal_period',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_plans_title', table_name='plans')
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'magazine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'next_renewal_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_column('subscriptions', 'price_at_renewal')
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.add_column('subscriptions', sa.Column('price_at_renewal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'next_renewal_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'magazine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscriptions', 'price')
    op.create_index('ix_plans_title', 'plans', ['title'], unique=False)
    op.alter_column('plans', 'renewal_period',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('magazines', sa.Column('discount_monthly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_magazines_name'), table_name='magazines')
    op.create_index('ix_magazines_name', 'magazines', ['name'], unique=False)
    op.alter_column('magazines', 'discount_annual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('magazines', 'discount_half_yearly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('magazines', 'discount_quarterly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('magazines', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('magazines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
