"""Update model definition

Revision ID: 8bb5f161fea5
Revises: 54f3008e1692
Create Date: 2024-08-06 13:12:54.508012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb5f161fea5'
down_revision: Union[str, None] = '54f3008e1692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('magazines', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('magazines', 'discount_quarterly')
    op.drop_column('magazines', 'discount_half_yearly')
    op.drop_column('magazines', 'discount_annual')
    op.add_column('plans', sa.Column('tier', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('discount', sa.Float(), nullable=False))
    op.alter_column('plans', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_plans_title'), 'plans', ['title'], unique=True)
    op.add_column('subscriptions', sa.Column('renewal_date', sa.Date(), nullable=False))
    op.drop_column('subscriptions', 'next_renewal_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('next_renewal_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'renewal_date')
    op.drop_index(op.f('ix_plans_title'), table_name='plans')
    op.alter_column('plans', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('plans', 'discount')
    op.drop_column('plans', 'tier')
    op.add_column('magazines', sa.Column('discount_annual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('magazines', sa.Column('discount_half_yearly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('magazines', sa.Column('discount_quarterly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('magazines', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
